import type { Metadata } from 'next';
import Link from 'next/link';
import { contentCategories } from './content-data';

export const metadata: Metadata = {
  title: 'Conteúdos sobre contabilidade e gestão | MDCon',
  description: 'Orientações da MDCon sobre abertura de empresas, impostos, departamento pessoal, Imposto de Renda, produtor rural e gestão empresarial.',
};

export default function Conteudos(){return <main className="content-hub">
<style>{`
.content-hub{background:#fff;color:#161616}.cw{width:min(1120px,calc(100% - 40px));margin:auto}.chero{padding:64px 0 54px;background:linear-gradient(180deg,#fff,#fbfbf8);border-bottom:1px solid #eee}.ey{color:#FFC400;font-size:12px;font-weight:900;letter-spacing:1.5px}.chero h1{max-width:800px;margin:14px 0 18px;font-size:clamp(40px,4.2vw,54px);line-height:1.04;letter-spacing:-2.4px}.chero p{max-width:760px;color:#606060;font-size:17px;line-height:1.7}.cats{padding:58px 0 72px}.cat{padding:30px 0;border-bottom:1px solid #e8e8e4;display:grid;grid-template-columns:.8fr 1.2fr;gap:55px}.cat h2{margin:0 0 10px;font-size:28px;line-height:1.12}.cat>div>p{margin:0;color:#666;line-height:1.65}.alist{display:grid;gap:10px}.alink{display:flex;justify-content:space-between;gap:20px;padding:15px 17px;border:1px solid #e5e5e1;border-radius:12px;color:#161616;text-decoration:none;font-weight:750;line-height:1.35}.alink:hover{border-color:#FFC400;transform:translateY(-1px)}.all{display:inline-block;margin-top:14px;color:#9a7600;font-weight:850;text-decoration:none}.cta{margin-top:50px;padding:30px 34px;background:#181818;color:#fff;border-radius:22px;display:flex;justify-content:space-between;align-items:center;gap:25px}.cta h2{margin:0 0 7px;font-size:28px}.cta p{margin:0;color:#ccc}.cta a{flex:none;background:#FFC400;color:#111;text-decoration:none;font-weight:900;padding:15px 20px;border-radius:11px}@media(max-width:760px){.cw{width:calc(100% - 28px)}.chero{padding:44px 0 38px}.chero h1{font-size:36px}.cat{grid-template-columns:1fr;gap:20px;padding:25px 0}.cta{flex-direction:column;align-items:flex-start;padding:25px 22px}.cta a{width:100%;box-sizing:border-box;text-align:center}}
`}</style>
<section className="chero"><div className="cw"><span className="ey">CONTEÚDOS</span><h1>Informação para quem cuida de um negócio.</h1><p>Orientações sobre contabilidade, impostos, empresas e gestão, organizadas para facilitar a consulta e ajudar você a entender melhor decisões importantes do dia a dia.</p></div></section>
<section className="cats"><div className="cw">{contentCategories.map((c,i)=><section className="cat" key={c.slug}><div><span className="ey">0{i+1}</span><h2>{c.title}</h2><p>{c.description}</p><Link className="all" href={`/conteudos/${c.slug}`}>Ver todos os conteúdos →</Link></div><div className="alist">{c.articles.map(a=><Link className="alink" href={`/conteudos/${c.slug}/${a.slug}`} key={a.slug}><span>{a.title}</span><span>→</span></Link>)}</div></section>)}<div className="cta"><div><h2>Ficou com alguma dúvida?</h2><p>Converse com a equipe da MDCon e explique sua situação.</p></div><a href="https://wa.me/5555984522204?text=Olá%20MDCon,%20tenho%20uma%20dúvida%20e%20gostaria%20de%20falar%20com%20a%20equipe." target="_blank" rel="noreferrer">Falar com a MDCon</a></div></div></section>
</main>}
