import type { Metadata } from 'next';
import Link from 'next/link';
import { notFound } from 'next/navigation';

const services = {
  'contabilidade-empresarial': { title:'Contabilidade Empresarial', intro:'Organização contábil para acompanhar a realidade da sua empresa.', description:'A MDCon realiza a escrituração e o acompanhamento contábil, organizando informações que apoiam a rotina e as decisões da empresa.', points:['Escrituração e acompanhamento contábil','Organização das informações da empresa','Suporte para compreensão da situação contábil','Atendimento próximo e orientação profissional'] },
  'abertura-de-empresas': { title:'Constituição e Abertura de Empresas', intro:'Orientação para começar sua empresa de forma organizada.', description:'A MDCon orienta o processo de constituição e abertura de empresas, auxiliando na organização dos documentos e nos primeiros passos do novo negócio.', points:['Orientação para constituição da empresa','Organização da documentação necessária','Apoio nos procedimentos de abertura','Orientação inicial sobre a rotina contábil do negócio'] },
  'escrituracao-fiscal': { title:'Escrituração Fiscal', intro:'Acompanhamento das obrigações fiscais da sua empresa.', description:'A MDCon acompanha a escrituração fiscal, a apuração de tributos e a organização das informações tributárias conforme a atividade da empresa.', points:['Escrituração fiscal','Apuração de tributos','Acompanhamento de obrigações fiscais','Organização das informações tributárias'] },
  'departamento-pessoal': { title:'Departamento Pessoal', intro:'Apoio nas rotinas trabalhistas da sua empresa.', description:'A MDCon auxilia empresas nas rotinas de departamento pessoal, acompanhando processos relacionados aos colaboradores e às obrigações trabalhistas.', points:['Folha de pagamento','Admissões e desligamentos','Rotinas e obrigações trabalhistas','Organização das informações dos colaboradores'] },
  'imposto-de-renda-pessoa-fisica': { title:'Imposto de Renda Pessoa Física', intro:'Orientação para organizar e elaborar sua declaração.', description:'A MDCon orienta e elabora a declaração de Imposto de Renda Pessoa Física de acordo com o perfil do contribuinte e as informações apresentadas.', points:['Organização das informações para a declaração','Elaboração da declaração de IRPF','Orientação conforme o perfil do contribuinte','Acompanhamento das informações declaradas'] },
  'planejamento-tributario': { title:'Planejamento Tributário', intro:'Análise tributária para decisões mais organizadas.', description:'A MDCon analisa possibilidades tributárias aplicáveis ao negócio, considerando sua realidade e buscando mais organização e segurança nas decisões.', points:['Análise da realidade tributária da empresa','Avaliação das possibilidades aplicáveis ao negócio','Orientação para decisões tributárias','Acompanhamento profissional'] },
  'assessoria-ao-produtor-rural': { title:'Assessoria ao Produtor Rural', intro:'Orientação contábil considerando as particularidades da atividade rural.', description:'A MDCon oferece apoio contábil ao produtor rural, auxiliando na organização das informações e no acompanhamento das obrigações relacionadas à atividade.', points:['Orientação contábil ao produtor rural','Organização de informações da atividade','Acompanhamento de obrigações','Atendimento conforme as particularidades do produtor'] },
  'certificado-digital': { title:'Certificado Digital', intro:'Certificação digital para pessoas físicas e empresas.', description:'A MDCon auxilia na emissão de certificado digital, utilizado para assinaturas, acessos e procedimentos eletrônicos com segurança.', points:['Certificado digital para pessoa física','Certificado digital para empresas','Orientação no processo de emissão','Apoio para utilização em acessos e assinaturas eletrônicas'] },
} as const;

type Slug = keyof typeof services;
export function generateStaticParams(){ return Object.keys(services).map(slug=>({slug})); }
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{ const {slug}=await params; const s=services[slug as Slug]; if(!s)return{}; return {title:`${s.title} em Palmeira das Missões – RS`,description:`${s.description} Atendimento pela MDCon em Palmeira das Missões – RS e para empresas de todo o Brasil.`}; }
export default async function ServicePage({params}:{params:Promise<{slug:string}>}){ const {slug}=await params; const s=services[slug as Slug]; if(!s) notFound(); const wa=`https://wa.me/5555984522204?text=${encodeURIComponent('Olá MDCon, gostaria de informações sobre '+s.title+'.')}`; return <main className="detail"><section className="hero"><div className="wrap"><Link href="/servicos" className="back">← Serviços</Link><span className="eyebrow">MDCON • SERVIÇOS CONTÁBEIS</span><h1>{s.title}<br/><strong>em Palmeira das Missões.</strong></h1><p>{s.intro}</p><a className="button" href={wa} target="_blank" rel="noreferrer">Falar com a MDCon</a></div></section><section className="content"><div className="wrap grid"><div><span className="eyebrow">COMO PODEMOS AJUDAR</span><h2>Atendimento contábil próximo e organizado.</h2><p>{s.description}</p><p>A MDCon está em Palmeira das Missões – RS e atende clientes em todo o Brasil, mantendo comunicação próxima e orientação profissional.</p></div><div className="card"><h2>Este serviço pode incluir</h2><ul>{s.points.map(x=><li key={x}>{x}</li>)}</ul><a className="textlink" href={wa} target="_blank" rel="noreferrer">Conversar sobre este serviço →</a></div></div></section><style>{`.detail{background:#fff;color:#161616}.wrap{width:min(1120px,calc(100% - 40px));margin:0 auto}.hero{padding:42px 0 46px;background:linear-gradient(180deg,#fff,#fbfbf8);border-bottom:1px solid #eee}.back{display:block;width:max-content;margin-bottom:24px;color:#555;text-decoration:none;font-weight:700}.eyebrow{display:block;color:#FFC400;font-size:12px;font-weight:900;letter-spacing:1.5px;margin-bottom:12px}.hero h1{max-width:900px;margin:0;font-size:clamp(42px,5vw,66px);line-height:1.02;letter-spacing:-2.8px}.hero h1 strong{color:#FFC400}.hero p{max-width:720px;margin:18px 0 22px;color:#555;font-size:18px;line-height:1.65}.button{display:inline-block;background:#FFC400;color:#111;padding:17px 24px;border-radius:12px;text-decoration:none;font-weight:900}.content{padding:48px 0 64px}.grid{display:grid;grid-template-columns:1.05fr .95fr;gap:56px;align-items:start}.grid h2{font-size:34px;line-height:1.12;letter-spacing:-1.2px}.grid p{color:#5f5f5f;line-height:1.8;font-size:16px}.card{padding:32px;border:1px solid #e7e7e2;border-radius:22px;background:#fcfcfa}.card h2{font-size:25px;margin-top:0;color:#FFC400}.card ul{padding:0;margin:24px 0;list-style:none}.card li{padding:14px 0;border-bottom:1px solid #e8e8e3}.card li:before{content:'✓';color:#FFC400;font-weight:900;margin-right:10px}.textlink{color:#FFC400;font-weight:900;text-decoration:none}@media(max-width:760px){.wrap{width:min(100% - 28px,1120px)}.hero{padding:30px 0 36px}.back{margin-bottom:20px}.hero h1{font-size:40px;letter-spacing:-1.8px}.hero p{font-size:16px;margin:16px 0 20px}.grid{grid-template-columns:1fr;gap:28px}.content{padding:36px 0 48px}.grid h2{font-size:29px}.card{padding:24px 20px}.button{width:100%;box-sizing:border-box;text-align:center}}`}</style></main> }
